version: '3.9'
services:
    fastapi_roechling:
        image: roechling-office-fastapi-app:latest
        container_name: roechling-office-fastapi-app-container
        restart: always
        ports:
            - "8805:80"
        volumes:
            - /volume2/docker/roechling_office_fastapi_app/global.log:/app/global.log
            - /volume2/docker/roechling_office_fastapi_app/.env:/app/.env
            - /volume2/docker/roechling_office_fastapi_app/data:/app/data
            - /volume2/docker/roechling_office_fastapi_app/logs:/app/logs
        environment:
            - TZ=Europe/Prague