"""make sharepoint article division a plain string

Revision ID: 13d51c3e4b1f
Revises: 7d45e9b4c14c
Create Date: 2026-07-20 22:43:03.758574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13d51c3e4b1f'
down_revision: Union[str, Sequence[str], None] = '7d45e9b4c14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiosk_sharepoint_article_divisions', 'division',
               existing_type=mysql.ENUM('Group', 'Automotive', 'Industrial', 'Medical'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kiosk_sharepoint_article_divisions', 'division',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Group', 'Automotive', 'Industrial', 'Medical'),
               existing_nullable=False)
    # ### end Alembic commands ###
