"""fix fk ondelete cascade

Revision ID: 21a21190b227
Revises: c478178f2f27
Create Date: 2026-04-08 22:39:18.253894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "21a21190b227"
down_revision: Union[str, Sequence[str], None] = "c478178f2f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("kiosk_news_documents_ibfk_1"), "kiosk_news_documents", type_="foreignkey")
    op.create_foreign_key(None, "kiosk_news_documents", "kiosk_news_items", ["news_item_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "kiosk_news_documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("kiosk_news_documents_ibfk_1"), "kiosk_news_documents", "kiosk_news_items", ["news_item_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
