"""add possibilists module with categories items and documents

Revision ID: 692d79edb3d2
Revises: 4a3443cea3e9
Create Date: 2026-06-15 22:03:12.279749

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "692d79edb3d2"
down_revision: Union[str, Sequence[str], None] = "4a3443cea3e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kiosk_possibilist_categories",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=500), nullable=True),
        sa.Column("is_group", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "kiosk_possibilist_items",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("published_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", mysql.LONGTEXT(), nullable=False),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("is_visible", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("views", sa.Integer(), server_default="0", nullable=False),
        sa.Column("category_id", mysql.BIGINT(unsigned=True), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["kiosk_possibilist_categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kiosk_possibilist_documents",
        sa.Column("id", mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
        sa.Column("possibilist_item_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("type", sa.Enum("image", "file", "youtube", name="documenttype"), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["possibilist_item_id"],
            ["kiosk_possibilist_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kiosk_possibilist_documents")
    op.drop_table("kiosk_possibilist_items")
    op.drop_table("kiosk_possibilist_categories")
    # ### end Alembic commands ###
