"""add sharepoint article divisions table

Revision ID: 7d45e9b4c14c
Revises: f4cd2bdac98e
Create Date: 2026-07-20 22:29:15.402594

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d45e9b4c14c"
down_revision: Union[str, Sequence[str], None] = "f4cd2bdac98e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kiosk_sharepoint_article_divisions",
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("division", sa.Enum("Group", "Automotive", "Industrial", "Medical", name="division"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["kiosk_sharepoint_articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "division"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kiosk_sharepoint_article_divisions")
    # ### end Alembic commands ###
