"""initial schema

Revision ID: 880da683bd4b
Revises: 
Create Date: 2026-03-31 20:21:57.945874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '880da683bd4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_book', 'pdf_file',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest_book', 'pdf_file',
               existing_type=sa.LargeBinary(),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
