"""add sort_order to possibilist categories

Revision ID: b44cde4010a5
Revises: 692d79edb3d2
Create Date: 2026-06-15 22:31:41.192810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44cde4010a5'
down_revision: Union[str, Sequence[str], None] = '692d79edb3d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosk_possibilist_categories', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosk_possibilist_categories', 'sort_order')
    # ### end Alembic commands ###
