"""fix kiosk news documents index and fk

Revision ID: c478178f2f27
Revises: a1b2c3d4e5f6
Create Date: 2026-04-08 22:37:59.682382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c478178f2f27"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MySQL requires dropping FK before dropping the index it depends on
    op.drop_constraint(op.f("kiosk_news_documents_ibfk_1"), "kiosk_news_documents", type_="foreignkey")
    op.drop_index(op.f("ix_kiosk_news_documents_news_item_id"), table_name="kiosk_news_documents")
    op.create_foreign_key(None, "kiosk_news_documents", "kiosk_news_items", ["news_item_id"], ["id"], ondelete="CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "kiosk_news_documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("kiosk_news_documents_ibfk_1"), "kiosk_news_documents", "kiosk_news_items", ["news_item_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(op.f("ix_kiosk_news_documents_news_item_id"), "kiosk_news_documents", ["news_item_id"], unique=False)
    # ### end Alembic commands ###
