"""add views to kiosk team members

Revision ID: dfbff7ce3dfb
Revises: 79a7e7f1b048
Create Date: 2026-09-23 21:24:59.758457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbff7ce3dfb'
down_revision: Union[str, Sequence[str], None] = '79a7e7f1b048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosk_team_members', sa.Column('views', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosk_team_members', 'views')
    # ### end Alembic commands ###
